import type { ThingsToDoSeedRow } from "./things-to-do-seed-types";

/** 60 new curated rows for Beaufort area — append-only; titles must stay unique across full seed. */
export const thingsToDoAddBeaufort: ThingsToDoSeedRow[] = [
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Breakwater Restaurant & Bar",
    description: "Harbor-view dining with sushi, steaks, and a lively wraparound porch.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Griffin Market",
    description: "Wine shop and bistro with seasonal plates and cheese boards.",
    venue: "Downtown Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Bricks on Boundary",
    description: "Neighborhood spot for brick-oven pizzas, salads, and craft beer.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Hemingway's Bistro",
    description: "European-inspired bistro plates and an intimate dining room.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Old Bull Tavern",
    description: "Gastropub favorites, whiskey list, and late-night small plates.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Q on Bay",
    description: "Lowcountry barbecue, smoked wings, and bourbon cocktails.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Saltus Sunset Deck",
    description: "Waterfront patio extension known for sunset drinks and seafood towers.",
    venue: "Henry C. Chambers Waterfront Park",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Dockside Beaufort",
    description: "Casual marina restaurant with fried seafood baskets and cold beer.",
    venue: "Beaufort Marina",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Plums Ice Cream Parlor",
    description: "House-made ice cream scoops and waffle cones steps from the park.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Blackstone's Coffeehouse",
    description: "Espresso drinks, breakfast sandwiches, and pastry case favorites.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Lowcountry Produce Market & Cafe",
    description: "Farmstand produce with a cafe counter for soups, sandwiches, and pies.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Brasserie Le Chocolat",
    description: "French pastries, bonbons, and dessert wines in a cozy shop.",
    venue: "Downtown Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Salt Marsh Brewing Beaufort",
    description: "Taproom with rotating IPAs and food pop-ups on weekends.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "The Foolish Frog",
    description: "St. Helena seafood shack with fried platters and outdoor picnic tables.",
    venue: "St. Helena Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Johnson Creek Tavern",
    description: "Local dive with burgers, cold beer, and porch sunsets over the marsh.",
    venue: "Lady's Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Beaufort Charcuterie Boardwalk",
    description: "Wine bar with charcuterie boards and harbor breezes.",
    venue: "Waterfront Park",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Sweetgrass Restaurant",
    description: "Southern tasting menus with Lowcountry ingredients and wine pairings.",
    venue: "Dataw Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Panini's on the Waterfront",
    description: "Pressed sandwiches, salads, and espresso overlooking the boats.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Ladys Island Oysters",
    description: "Raw bar and grilled oysters with local beer on tap.",
    venue: "Lady's Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "The Fillin' Station Port Royal",
    description: "Retro diner with breakfast all day and milkshakes at the counter.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Gullah Grub Restaurant",
    description: "Traditional Gullah plates and fresh seafood on St. Helena.",
    venue: "St. Helena Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Herban Kitchen & Juicery",
    description: "Smoothie bowls, wraps, and organic groceries in one stop.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Scout Southern Market Cafe",
    description: "Light lunch bites inside a gift and home boutique.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Beaufort Bread Company",
    description: "Sourdough loaves, viennoiserie, and pour-over coffee bar.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "The Foolish Burger",
    description: "Smash burgers, hand-cut fries, and milkshakes from a walk-up window.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Port Royal Smokehouse",
    description: "Pulled pork, brisket, and ribs with vinegar slaw and hushpuppies.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Bay Street Burritos",
    description: "Fast-casual burritos, bowls, and margarita pitchers.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "The Anchor Room",
    description: "Nautical-themed cocktail lounge with small plates and harbor views.",
    venue: "Downtown Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Lowcountry Cider House",
    description: "Regional hard ciders, flights, and cheese pairings on the patio.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Marshside Grill",
    description: "Casual seafood platters and fried green tomatoes near the bridge.",
    venue: "Lady's Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "The Rusty Mug",
    description: "Coffee roastery with single-origin beans and weekend brunch.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Shellring Ale Works",
    description: "Microbrewery taproom with outdoor games and food trucks.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Hunting Island Beach Snack Bar",
    description: "Beach-day snacks, ice cream, and cold drinks at the state park.",
    venue: "Hunting Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Beaufort Bonito Sushi",
    description: "Fresh rolls, poke bowls, and sake in a minimalist dining room.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Outdoors & Nature",
    title: "Hunting Island Lighthouse Climb",
    description: "Climb the lighthouse steps for Atlantic views over the maritime forest.",
    venue: "Hunting Island State Park",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Outdoors & Nature",
    title: "Cypress Wetlands Trail",
    description: "Boardwalk loop through cypress domes with alligator viewing.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Outdoors & Nature",
    title: "Beaufort Riverwalk Extension",
    description: "Extended waterfront path connecting marinas and pocket parks.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Water Sports",
    title: "Lady's Island Marina Kayak Rentals",
    description: "Hourly kayak and SUP rentals to explore the Beaufort River.",
    venue: "Lady's Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Water Sports",
    title: "Beaufort Sport Fishing Charters",
    description: "Nearshore and inshore trips for trout, redfish, and flounder.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "History & Tours",
    title: "Beaufort Arsenal Museum",
    description: "Military artifacts and exhibits inside a historic tabby arsenal.",
    venue: "Craven Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "History & Tours",
    title: "Robert Smalls House Tour",
    description: "Guided interpretation of the Reconstruction leader’s historic home.",
    venue: "Prince Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "History & Tours",
    title: "St. Helena Chapel of Ease Cemetery Walk",
    description: "Quiet cemetery paths among live oaks and historic markers.",
    venue: "St. Helena Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Arts & Culture",
    title: "USCB Performing Arts Mainstage",
    description: "Theater, dance, and touring acts at the university arts center.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Arts & Culture",
    title: "Gullah Art Collective Gallery",
    description: "Rotating exhibits of Sea Island fiber art, sweetgrass baskets, and painting.",
    venue: "St. Helena Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Shopping",
    title: "Bay Street Antiques Row",
    description: "Cluster of antique shops with furniture, glassware, and coastal finds.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Shopping",
    title: "Beaufort Olive Oil Company",
    description: "Infused oils, vinegars, and tasting bar for hostess gifts.",
    venue: "Downtown Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Golf",
    title: "Secession Golf Club",
    description: "Private coastal course with wide dunes and ocean breezes.",
    venue: "Beaufort",
    website: "https://www.secessiongolfclub.com",
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Golf",
    title: "Ocean Point Golf Links",
    description: "Public-friendly layout with marsh carries and Lowcountry views.",
    venue: "Lady's Island",
    website: "https://www.oceanpointgolf.com",
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Family & Kids",
    title: "Beaufort Pirate Adventures",
    description: "Family boat ride with pirate actors and water cannon battles.",
    venue: "Beaufort Waterfront",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Family & Kids",
    title: "Port Royal Skate Park",
    description: "Concrete skate plaza and pump track for boards and scooters.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Nightlife",
    title: "Plums Upstairs Lounge",
    description: "Late-night cocktails above the main dining room with harbor breezes.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Nightlife",
    title: "Bay Street Blues Beaufort",
    description: "Live blues bands and dancing on weekend nights.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Fitness & Wellness",
    title: "Beaufort Yoga & Wellness",
    description: "Heated studio classes, meditation workshops, and massage referrals.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "General",
    title: "Beaufort Visitors Center",
    description: "Trip planning, maps, and event info for the Sea Islands.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "General",
    title: "Parris Island Visitor Station",
    description: "Scheduled family days and museum access for Marine Corps history.",
    venue: "Parris Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Dockside Waterfront Bar",
    description: "Open-air bar with frozen drinks and peel-and-eat shrimp.",
    venue: "Henry C. Chambers Waterfront Park",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Food & Drink",
    title: "Bay Street Provisions",
    description: "Gourmet sandwiches, wine retail, and cheese boards to go.",
    venue: "Bay Street, Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Outdoors & Nature",
    title: "Sands Beach Boardwalk",
    description: "Stroll the Port Royal boardwalk at golden hour with dolphin sightings.",
    venue: "Port Royal",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Water Sports",
    title: "Beaufort Stand Up Paddle",
    description: "Lessons and rentals on the calm waters of the Beaufort River.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
  {
    market_key: "beaufort",
    category: "Arts & Culture",
    title: "Beaufort Film Society Screenings",
    description: "Independent and classic films in intimate downtown venues.",
    venue: "Beaufort",
    website: null,
    source: "curated",
  },
];
