/** Curated sample rows for `things_to_do` (verify offers with venues). Upserted on `title`. */
export const thingsToDoSeedData = [
  // Hilton Head Island
  { icon: null, market_key: "hhi", badge: "30% OFF", title: "Dolphin Kayak Tour", description: "2-hour guided kayak tour through the salt marshes with dolphin spotting.", venue: "Outside Hilton Head", expires: "Expires Apr 30", source: "manual" },
  { icon: null, market_key: "hhi", badge: "$20 OFF", title: "Round of Golf — Harbour Town", description: "Twilight round discount every day after 3 PM. Cart included.", venue: "Sea Pines Resort", expires: "Weekdays only", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FREE", title: "Guided Nature Walk — Pinckney Island", description: "Saturday morning walks through the Pinckney Island Wildlife Refuge.", venue: "US Fish & Wildlife Service", expires: "Every Saturday 8 AM", source: "manual" },
  { icon: null, market_key: "hhi", badge: "BOGO", title: "Happy Hour at Skull Creek Dockside", description: "Buy one cocktail, get one free every day 3–6 PM on the waterfront deck.", venue: "Skull Creek Dockside", expires: "Daily 3–6 PM", source: "manual" },
  { icon: null, market_key: "hhi", badge: "15% OFF", title: "Art Classes at Arts Center of Coastal Carolina", description: "Watercolor, pottery, and mixed media classes for all skill levels.", venue: "Hilton Head", expires: "Spring session", source: "manual" },
  { icon: null, market_key: "hhi", badge: "25% OFF", title: "Surf Lessons for Beginners", description: "Board rental + 90-min lesson at Folly Field Beach. Great for families.", venue: "Hilton Head Surf Co.", expires: "Expires May 15", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FREE", title: "Coligny Beach Park & Plaza", description: "Boardwalks, showers, and summer music near Coligny Circle.", venue: "Coligny Beach, HHI", expires: "Year-round", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FROM $35", title: "Harbour Town Lighthouse Climb", description: "Iconic striped lighthouse with views of Calibogue Sound.", venue: "Sea Pines — Harbour Town", expires: "Hours vary", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FREE", title: "Shelter Cove Harbour Summer Fireworks", description: "Fireworks over the marina — arrive early for dinner.", venue: "Shelter Cove Towne Centre", expires: "Tuesdays in season", source: "manual" },
  { icon: null, market_key: "hhi", badge: "10% OFF", title: "Bike Rental — Leisure Trails", description: "Explore 60+ miles of flat paths; helmets and maps included.", venue: "Island bike shops", expires: "Book ahead", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FREE", title: "Mitchelville Freedom Park", description: "Interpretive trails on a historic Freedmen’s community site.", venue: "Fish Haul Creek area, HHI", expires: "Dawn to dusk", source: "manual" },
  { icon: null, market_key: "hhi", badge: "20% OFF", title: "Stand-Up Paddleboard Eco Tour", description: "Calm-water intro through Broad Creek marshes.", venue: "Broad Creek, HHI", expires: "Morning & sunset", source: "manual" },
  { icon: null, market_key: "hhi", badge: "FREE", title: "Jarvis Creek Park Pier", description: "Quiet fishing pier and trails — great for families.", venue: "Jarvis Creek, HHI", expires: "Year-round", source: "manual" },
  { icon: null, market_key: "hhi", badge: "KIDS FREE", title: "Coastal Discovery Museum", description: "Honey Horn campus: exhibits, butterfly enclosure, and trails.", venue: "Coastal Discovery Museum", expires: "See calendar", source: "manual" },
  // Bluffton
  { icon: null, market_key: "bluffton", badge: "FREE", title: "Old Town Bluffton Art Walk", description: "Galleries open late; meet artists on the May River.", venue: "Calhoun Street, Bluffton", expires: "Second Thursdays", source: "manual" },
  { icon: null, market_key: "bluffton", badge: "FARM", title: "Bluffton Farmers Market", description: "Produce, seafood, baked goods, and music under the oaks.", venue: "Martin Family Park", expires: "Thursdays 12–5 PM", source: "manual" },
  { icon: null, market_key: "bluffton", badge: "LIVE", title: "Music on the May", description: "Outdoor concerts overlooking the river in the heart of Old Town.", venue: "Bluffton Waterfront", expires: "Seasonal Fridays", source: "manual" },
  { icon: null, market_key: "bluffton", badge: "TOUR", title: "Heyward House Historic Center", description: "Antebellum home and walking maps of Old Town Bluffton.", venue: "Heyward House", expires: "Wed–Sat", source: "manual" },
  { icon: null, market_key: "bluffton", badge: "FREE", title: "Oscar Frazier Park Splash Pad", description: "Family-friendly play and picnic space near Buckwalter.", venue: "Bluffton", expires: "Seasonal hours", source: "manual" },
  { icon: null, market_key: "bluffton", badge: "15% OFF", title: "Kayak the May River", description: "Guided paddles from Bluffton landings at golden hour.", venue: "Bluffton outfitters", expires: "Book ahead", source: "manual" },
  // Beaufort
  { icon: null, market_key: "beaufort", badge: "TOUR", title: "Historic Beaufort Walking Tour", description: "Antebellum homes, film locations, and Lowcountry stories.", venue: "Downtown Beaufort", expires: "Weekend departures", source: "manual" },
  { icon: null, market_key: "beaufort", badge: "FREE", title: "Henry C. Chambers Waterfront Park", description: "Swing benches, playground, and views of the Beaufort River.", venue: "Bay Street, Beaufort", expires: "Daily", source: "manual" },
  { icon: null, market_key: "beaufort", badge: "MUSEUM", title: "Parris Island Museum", description: "Marine Corps history exhibits (off-base visitor access rules apply).", venue: "Parris Island", expires: "Check hours", source: "manual" },
  { icon: null, market_key: "beaufort", badge: "BOAT", title: "Hunting Island State Park Day Trip", description: "Lighthouse, beach, and maritime forest — short drive from Beaufort.", venue: "Hunting Island", expires: "Park hours", source: "manual" },
  { icon: null, market_key: "beaufort", badge: "FREE", title: "Spanish Moss Trail", description: "Paved rail-trail for bikes and strollers through the Lowcountry.", venue: "Beaufort area", expires: "Dawn to dusk", source: "manual" },
  // Savannah
  { icon: null, market_key: "savannah", badge: "FROM $28", title: "Savannah Riverboat Sightseeing", description: "Narrated cruise on the Savannah River past the port and historic district.", venue: "River Street", expires: "Multiple daily", source: "manual" },
  { icon: null, market_key: "savannah", badge: "FREE", title: "Forsyth Park Fountain Stroll", description: "Iconic fountain, farmer’s market Saturdays, and wide live oaks.", venue: "Forsyth Park", expires: "Year-round", source: "manual" },
  { icon: null, market_key: "savannah", badge: "WALK", title: "Historic Squares Self-Guided Walk", description: "22 squares, each with its own story — start at Johnson Square.", venue: "Savannah Historic District", expires: "Anytime", source: "manual" },
  { icon: null, market_key: "savannah", badge: "MUSEUM", title: "Telfair Museums Campus", description: "Jepson, Telfair Academy, and Owens-Thomas House — art and architecture.", venue: "Telfair Square area", expires: "Closed Mondays", source: "manual" },
  { icon: null, market_key: "savannah", badge: "FOOD", title: "River Street Sweets & River Walk", description: "Pralines, candy kitchen views, and cobblestone riverfront.", venue: "River Street", expires: "Daily", source: "manual" },
];
