import type { ThingsToDoSeedRow } from "./things-to-do-seed-types";

/** 60 new curated rows for Hilton Head Island — append-only; titles must stay unique across full seed. */
export const thingsToDoAddHhi: ThingsToDoSeedRow[] = [
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "One Hot Mama's American Grille",
    description:
      "Wood-fired steaks, ribs, and burgers with a lively bar scene near the Sea Pines gate.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Frankie Bones",
    description: "Italian-American classics, generous plates, and a popular bar crowd.",
    venue: "Park Plaza, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Charbar Co. Burger & Sushi Bar",
    description: "Gourmet burgers and sushi rolls under one roof with a casual vibe.",
    venue: "Shelter Cove area, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Kenny B's French Quarter Cafe",
    description: "Creole-inspired seafood and po’boys with a New Orleans feel.",
    venue: "South End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Bullies BBQ",
    description: "Slow-smoked barbecue, sandwiches, and classic Southern sides.",
    venue: "William Hilton Parkway, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Alexander's Restaurant & Wine Bar",
    description: "Upscale seafood and steaks with an extensive wine list.",
    venue: "Main Street, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "The Black Marlin Bar & Grill",
    description: "Casual seafood house with a popular patio and raw bar.",
    venue: "Palmetto Bay Marina, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Chow Daddy's",
    description: "Asian-inspired small plates, ramen, and craft cocktails.",
    venue: "Sea Pines Centre, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Lucky Rooster Kitchen + Bar",
    description: "Southern comfort plates and brunch with a polished dining room.",
    venue: "New Orleans Road, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Big Jim's BBQ Burgers & Pizza",
    description: "Family-friendly spot for pizza, burgers, and barbecue favorites.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Reilley's North End Pub",
    description: "Irish pub grub, live music, and a laid-back North End crowd.",
    venue: "North End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Coastal Provisions",
    description: "Seafood-focused menu with raw bar options and Lowcountry flavors.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Giuseppi's Pizza & Pasta House",
    description: "Thin-crust pizza and Italian pastas in a longtime island favorite.",
    venue: "Matthews Drive, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "The French Bakery & European Cuisine",
    description: "Pastries, espresso, and European-style breakfast and lunch plates.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Stu's Surfside Subs",
    description: "Hearty subs and sandwiches popular with beachgoers and locals.",
    venue: "South End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Bomboras Grille",
    description: "Island-inspired plates and tropical drinks with a fun atmosphere.",
    venue: "Coligny Plaza, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Holy Tequila",
    description: "Mexican street fare, tacos, and a long tequila list.",
    venue: "Shelter Cove, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Aunt Chilada's Easy Street Cafe",
    description: "Casual Mexican and American dishes steps from the beach.",
    venue: "South Forest Beach, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Coast Oceanfront Dining",
    description: "Ocean views and contemporary seafood inside Sea Pines Resort.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "The Studio",
    description: "Chef-driven New American plates in an intimate dining room.",
    venue: "New York Avenue, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Rio Chico Mexican Restaurant",
    description: "Tex-Mex classics, margaritas, and family-sized combo platters.",
    venue: "William Hilton Parkway, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Mi Tierra Mexican Restaurant",
    description: "Authentic Mexican plates and weekend brunch with strong margaritas.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Poseidon Coastal Cuisine",
    description: "Seafood towers, sushi, and harbor-facing seating at Shelter Cove.",
    venue: "Shelter Cove, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Salty Dog Cafe",
    description: "Iconic South Beach Marina cafe known for casual bites and T-shirt culture.",
    venue: "South Beach Marina, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Fishcamp on Broad Creek",
    description: "Broad Creek waterfront dining with Lowcountry seafood and steaks.",
    venue: "Broad Creek, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "The Quarterdeck",
    description: "Waterfront seafood and steaks with sunset views over Skull Creek.",
    venue: "Skull Creek, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Links an American Grill",
    description: "Prime steaks and seafood at Palmetto Dunes with a polished grill-room feel.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Local Pie Hilton Head",
    description: "Wood-fired pizzas and salads with seasonal toppings.",
    venue: "New York City Pizza Plaza, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Sage Room Restaurant & Bar",
    description: "Steakhouse favorites and cocktails in a warm, clubby setting.",
    venue: "South End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Catch 22",
    description: "Casual seafood spot known for daily fish specials and sandwiches.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "San Miguel's Mexican Cafe",
    description: "Sizzling fajitas, enchiladas, and margaritas in a festive room.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Masala Mantra Indian Bistro",
    description: "Indian curries, tandoor dishes, and vegetarian options in Wexford.",
    venue: "Wexford Village, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Signe's Heaven Bound Bakery & Cafe",
    description: "Scratch-made pastries, quiche, and brunch plates beloved by locals.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "ELA's Blu Water Grille",
    description: "Fine dining with Blu water views and chef-driven seafood plates.",
    venue: "Shelter Cove, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Dye's Gullah Fixin's",
    description: "Gullah Geechee-inspired soul food and storytelling dinners.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Watusi",
    description: "Pan-Asian fusion with sushi, noodles, and creative cocktails.",
    venue: "Folly Field, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Nectar Farm Kitchen",
    description: "Farm-to-table breakfast and lunch with fresh juices and bowls.",
    venue: "William Hilton Parkway, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Ocean Lounge",
    description: "Upscale lounge for seafood small plates and cocktails near the ocean.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Annie O's Kitchen",
    description: "Southern breakfast and lunch with hearty plates and friendly service.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Pomodori Italian Restaurant",
    description: "Classic Italian pastas, parmigianas, and house wine in a cozy room.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "OKKO Japanese Sushi & Hibachi",
    description: "Hibachi tables, sushi bar, and Japanese entrees for families and groups.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Deano's Wood Fired Grille",
    description: "Wood-fired pizzas, pastas, and steaks in a relaxed dining room.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Food & Drink",
    title: "Local Legend Brewing Company",
    description: "New South brewery taproom with burgers, wings, and live music.",
    venue: "South End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "George Fazio Golf Course",
    description: "Challenging resort course with tight fairways and coastal breezes.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "Arthur Hills Golf Course",
    description: "Rolling Palmetto Dunes layout with water on nearly every hole.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "Oyster Reef Golf Club",
    description: "Rees Jones design with ocean breezes and memorable par threes.",
    venue: "Shipyard Plantation, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "Robert Trent Jones Oceanfront Course",
    description: "Oceanfront holes and wide fairways at Palmetto Dunes Resort.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "Heron Point by Pete Dye",
    description: "Strategic Pete Dye redesign with risk-reward shots at Sea Pines.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Golf",
    title: "Dolphin Head Golf Club",
    description: "Public-friendly course with mossy oaks and forgiving fairways.",
    venue: "North End, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Beaches & Parks",
    title: "Singleton Beach Park",
    description: "Neighborhood beach access with parking and wide Atlantic views.",
    venue: "Singleton Beach, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Beaches & Parks",
    title: "Burkes Beach Park",
    description: "Quiet beach access with picnic tables and seasonal lifeguards.",
    venue: "Burkes Beach Road, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Beaches & Parks",
    title: "Islanders Beach Park",
    description: "Family beach with playground, showers, and seasonal facilities.",
    venue: "Folly Field, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Outdoors & Nature",
    title: "Leamington Lighthouse",
    description: "Historic lighthouse viewing and interpretive walks in Sea Pines.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Outdoors & Nature",
    title: "Zion Cemetery & Baynard Ruins",
    description: "Historic cemetery and tabby ruins along a shaded Sea Pines trail.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Water Sports",
    title: "Outside Hilton Head",
    description: "Kayak, paddleboard, and boat tours with naturalist guides.",
    venue: "Broad Creek, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Water Sports",
    title: "Palmetto Dunes Lagoon Fishing & Boating",
    description: "Calm 11-mile lagoon for kayaking, canoeing, and small-craft boating.",
    venue: "Palmetto Dunes, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Water Sports",
    title: "Vagabond Cruise",
    description: "Narrated dolphin and sightseeing cruises from Shelter Cove Marina.",
    venue: "Shelter Cove, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Arts & Culture",
    title: "Hilton Head Symphony Orchestra",
    description: "Classical pops and guest artists at venues around the island.",
    venue: "Hilton Head Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Arts & Culture",
    title: "Art League of Hilton Head",
    description: "Member gallery, workshops, and rotating exhibits of regional art.",
    venue: "Arts Center area, HHI",
    website: null,
    source: "curated",
  },
  {
    market_key: "hhi",
    category: "Family & Kids",
    title: "Lawton Stables",
    description: "Trail rides, pony time, and animal encounters in Sea Pines.",
    venue: "Sea Pines, HHI",
    website: null,
    source: "curated",
  },
];
