import type { ThingsToDoSeedRow } from "./things-to-do-seed-types";

/** 60 new curated rows for Bluffton — append-only; titles must stay unique across full seed. */
export const thingsToDoAddBluffton: ThingsToDoSeedRow[] = [
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Local Pie Bluffton",
    description: "Wood-fired pizzas and salads with seasonal toppings near Buckwalter.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "FARM Bluffton",
    description: "Scratch Southern kitchen with a lively bar and patio seating.",
    venue: "Bluffton Parkway",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Pearl Kitchen & Bar",
    description: "Oyster bar and coastal plates in a polished Old Town setting.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Captain Woody's Seafood Bar & Grill",
    description: "Casual seafood baskets, cold beer, and sports on TV.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Fat Patties",
    description: "Gourmet burgers, hand-cut fries, and milkshakes in a retro diner.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Tio's Latin American Kitchen",
    description: "Latin fusion plates, tacos, and margaritas with weekend brunch.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Agave Side Kitchen",
    description: "Southwestern flavors, tequila flights, and a shaded patio.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Sippin' Post",
    description: "Wine bar with small plates and Lowcountry cheese boards.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Bluffton Room",
    description: "Chef-driven American plates and craft cocktails in an intimate room.",
    venue: "Calhoun Street",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Millstone Kitchen",
    description: "Breakfast through dinner with biscuits, burgers, and local seafood.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Scott's Fish Market Restaurant",
    description: "Fresh catch, raw bar, and harbor breezes at Shelter Cove–style hospitality.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Greek Table",
    description: "Mediterranean mezze, gyros, and grilled seafood platters.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Okatie Ale House",
    description: "Sports bar with wings, burgers, and local brews on tap.",
    venue: "Okatie",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Cello's Courtyard Café",
    description: "Casual courtyard dining with pasta, salads, and live music nights.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Honey B's Eatery",
    description: "Southern breakfast and lunch with scratch biscuits and gravy.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Nectar Southern Kitchen Bluffton",
    description: "Southern plates and fresh juices in a bright, family-friendly room.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Juice Box Bluffton",
    description: "Cold-pressed juices, smoothies, and light health-focused bowls.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Donuts & Deli",
    description: "Morning donuts, breakfast sandwiches, and deli subs for grab-and-go.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Bluffton BBQ House",
    description: "Pulled pork, brisket, and ribs with classic vinegar and mustard sauces.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "May River Burrito Co.",
    description: "Build-your-own burritos, bowls, and street-style tacos.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Upper Crust Bluffton",
    description: "Artisan bread, sandwiches, and coffee in a neighborhood bakery.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Salt Marsh Brewing",
    description: "Small-batch brewery taproom with food trucks and outdoor seating.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Roasted Bean",
    description: "Specialty espresso, pour-overs, and pastries for remote workers.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Bluffton Fish Camp",
    description: "Lowcountry seafood shack with fried baskets and outdoor picnic tables.",
    venue: "May River",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Palmetto Brews Bluffton",
    description: "Craft beer flights, pretzels, and live acoustic weekends.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Southern Barrel",
    description: "Whiskey-forward bar with small plates and a deep bourbon list.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Olive & Fig Mediterranean Kitchen",
    description: "Hummus, kebabs, and fresh salads inspired by the eastern Mediterranean.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Truffles Bluffton Market",
    description: "Grab-and-go sandwiches, wine, and gourmet groceries.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Deck on May River",
    description: "Sunset cocktails and seafood small plates overlooking the bluff.",
    venue: "Calhoun Street",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Bluffton Public House",
    description: "Gastropub fare, local drafts, and trivia nights.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Lowcountry Boil Company — Bluffton",
    description: "Seasonal shrimp boils and catering-style seafood feasts to go.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Lost Local",
    description: "Neighborhood bar with craft cocktails and late-night snacks.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Bluffton Bagel & Deli",
    description: "Boiled bagels, schmears, and stacked deli sandwiches.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "May River Taqueria",
    description: "Street tacos, elote, and agua frescas in a colorful cantina.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Ice House Bluffton",
    description: "Oysters, crudos, and frozen cocktails in a restored ice-house setting.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Outdoors & Nature",
    title: "Victoria Bluff Heritage Preserve",
    description: "Pine flatwoods and shell ridges with quiet hiking loops.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Outdoors & Nature",
    title: "New River Linear Trail — South",
    description: "Paved segment through wetlands with birding overlooks.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Outdoors & Nature",
    title: "Alljoy Landing",
    description: "Public dock and green space for watching boats on the May River.",
    venue: "Alljoy",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Water Sports",
    title: "May River Excursions",
    description: "Guided boat tours, sunset cruises, and dolphin viewing from Bluffton docks.",
    venue: "May River",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Water Sports",
    title: "Headwaters Kayak Tours",
    description: "Tidal creek paddles through marsh grass and oyster beds.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "History & Tours",
    title: "Bluffton Tabby Ruins Walk",
    description: "Self-guided stroll past historic shell ruins and live oaks.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "History & Tours",
    title: "Garvin-Garvey Freedman's Cottage",
    description: "Restored Freedmen’s-era cottage with exhibits on Gullah heritage.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Arts & Culture",
    title: "SOBA Gallery",
    description: "Rotating member shows and juried exhibits along Calhoun Street.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Arts & Culture",
    title: "Bluffton School of Dance",
    description: "Performances and community dance classes in a historic studio.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Shopping",
    title: "Bluffton General Mercantile",
    description: "Gifts, pantry goods, and Lowcountry souvenirs in a general-store setting.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Shopping",
    title: "The Complete Home",
    description: "Home décor, coastal accents, and hostess gifts.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Family & Kids",
    title: "Bluffton Pool & Recreation Center",
    description: "Public pool, splash days, and youth programs seasonally.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Family & Kids",
    title: "Martin Family Park Splash Pad",
    description: "Seasonal splash pad and lawn games beside the farmers market.",
    venue: "Martin Family Park",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Golf",
    title: "Crescent Pointe Golf Club",
    description: "Arnold Palmer public design with generous fairways and water features.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Golf",
    title: "Old South Golf Links",
    description: "Lowcountry marsh views and classic Lowcountry layout.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Golf",
    title: "Eagle's Pointe Golf Club",
    description: "Player-friendly course with lakes and pine-lined corridors.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Nightlife",
    title: "Bluffton Speakeasy Room",
    description: "Craft cocktails and live jazz in a dim, intimate lounge.",
    venue: "Old Town Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Nightlife",
    title: "The Bank Beer Garden",
    description: "Outdoor beer garden with food trucks and weekend DJs.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Fitness & Wellness",
    title: "May River Yoga Studio",
    description: "Heated vinyasa, restorative classes, and workshops.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Fitness & Wellness",
    title: "Bluffton Salt Cave",
    description: "Halotherapy sessions in a relaxing salt-lined relaxation room.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "General",
    title: "Bluffton Visitor & Welcome Center",
    description: "Maps, brochures, and tips for exploring Old Town and the May River.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "General",
    title: "Buckwalter Place Town Center",
    description: "Mixed-use hub with shops, dining, and community events.",
    venue: "Buckwalter",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "The Juicy Crab — Bluffton",
    description: "Cajun seafood boils with corn, potato, and customizable spice levels.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Food & Drink",
    title: "Redfish Bluffton Waterfront",
    description: "River-view deck with grilled fish, tacos, and weekend brunch.",
    venue: "May River",
    website: null,
    source: "curated",
  },
  {
    market_key: "bluffton",
    category: "Outdoors & Nature",
    title: "Bluffton Oyster Reef Trail",
    description: "Short boardwalk and interpretive signs along restored oyster habitat.",
    venue: "Bluffton",
    website: null,
    source: "curated",
  },
];
