import type { ThingsToDoSeedRow } from "./things-to-do-seed-types";

/** 60 new curated rows for Savannah — append-only; titles must stay unique across full seed. */
export const thingsToDoAddSavannah: ThingsToDoSeedRow[] = [
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Olde Pink House Restaurant",
    description: "Lowcountry fine dining in a blush mansion with cellar bar and ghost stories.",
    venue: "Reynolds Square, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Husk Savannah",
    description: "Ingredient-driven Southern plates from heirloom grains and regional farms.",
    venue: "Historic District, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Alligator Soul",
    description: "Underground dining room with wild game, seafood, and an adventurous chef’s menu.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Collins Quarter",
    description: "Melbourne-style brunch, espresso, and cocktails on Bull Street.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Treylor Park",
    description: "Creative comfort food, nachos, and patio hangs in a quirky house.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Common Thread",
    description: "Seasonal tasting menus with open kitchen and wine pairings.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Cotton & Rye",
    description: "Modern Southern plates and craft cocktails in a restored midcentury space.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Green Truck Pub",
    description: "Grass-fed burgers, local beer, and a laid-back neighborhood crowd.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Crystal Beer Parlor",
    description: "Georgia’s oldest eatery pouring drafts with pub classics since 1933.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Vic's on the River",
    description: "River-view dining room known for she-crab soup and fried green tomatoes.",
    venue: "Savannah Riverfront",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Cha Bella",
    description: "Farm-to-table Italian with rooftop garden herbs and pastas.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Sorry Charlie's Oyster Bar",
    description: "Raw bar and seafood towers steps from Ellis Square.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Two Cracked Eggs Cafe",
    description: "Hearty breakfast lines and Southern staples in a cozy brick room.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Fox & Fig Cafe",
    description: "Plant-based brunch, espresso, and pastries on Troup Square.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Grey Market",
    description: "Counter-service deli, wine, and provisions from The Grey team.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Back in the Day Bakery",
    description: "Cupcakes, pies, and biscuits from a beloved Starland bakery.",
    venue: "Starland District, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Starland Yard",
    description: "Food-truck yard with bars, live music, and family-friendly lawn games.",
    venue: "Starland District, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Savannah Seafood Shack",
    description: "Paper-lined seafood boils, hushpuppies, and cold beer.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Rhett",
    description: "Coastal steak and seafood with a polished dining room on Broughton.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Elizabeth on 37th",
    description: "Seven-course tasting menus in a historic mansion with garden views.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Wyld Dock Bar",
    description: "Dockside seafood shack on the marsh with sunset platters and cocktails.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "B's Cracklin' BBQ",
    description: "Pit-smoked barbecue, ribs, and sides with a cult following.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Kayak Kafe Midtown",
    description: "Fresh bowls, wraps, and smoothies in a bright Midtown cafe.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Savannah Tequila Company",
    description: "Agave flights, margarita flights, and Latin small plates.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Atlantic",
    description: "Bright seafood house with raw bar and rooftop-adjacent dining.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Perc Coffee Roasters",
    description: "Third-wave espresso bar and beans roasted in-house.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Mirabelle Savannah",
    description: "Belgian waffles, liege sugar, and brunch cocktails downtown.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Savannah Candy Kitchen",
    description: "Pralines, saltwater taffy, and pecan logs along River Street.",
    venue: "River Street, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Huey's on the River",
    description: "New Orleans-style beignets, brunch, and live jazz weekends.",
    venue: "Savannah Riverfront",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Coastal Empire Beer Co.",
    description: "Taproom with core IPAs, sours, and weekend food trucks.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Two Tides Brewing Company",
    description: "Neighborhood nano-brewery with experimental small batches.",
    venue: "Starland District, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Ordinary Pub",
    description: "Gastropub with creative burgers, brunch, and craft cocktails.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Savannah Social",
    description: "Rooftop bar with frozen drinks and small plates overlooking Broughton.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "Belfast Love",
    description: "Irish pub with shepherd’s pie, pints, and soccer on the screens.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Outdoors & Nature",
    title: "Wormsloe Colonial Life Trail",
    description: "Nature trail beyond the oak avenue with marsh overlooks.",
    venue: "Isle of Hope",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Outdoors & Nature",
    title: "Oatland Island Wildlife Center",
    description: "Boardwalks past wolves, bobcats, and coastal birds on a quiet island.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Outdoors & Nature",
    title: "Tom Triplett Community Park",
    description: "Disc golf, fishing pier, and walking loops around the lake.",
    venue: "Pooler",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Water Sports",
    title: "Savannah Canoe & Kayak",
    description: "Guided marsh paddles and rentals on tidal creeks near Isle of Hope.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Water Sports",
    title: "Tybee Jet Ski & Watersports",
    description: "Jet ski rentals, banana boat rides, and parasail off Tybee’s beaches.",
    venue: "Tybee Island",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "History & Tours",
    title: "Owens-Thomas House Slave Quarters Tour",
    description: "Interpretive tours highlighting enslaved people’s lives in historic spaces.",
    venue: "Telfair Square, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "History & Tours",
    title: "Savannah Prohibition Museum",
    description: "Speakeasy exhibits, vintage cars, and cocktail history.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "History & Tours",
    title: "Mercer Williams House Tours",
    description: "Guided visits through the Italianate home made famous in Midnight in the Garden.",
    venue: "Monterey Square, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Arts & Culture",
    title: "Jepson Center for the Arts",
    description: "Contemporary art exhibitions and interactive family installations.",
    venue: "Telfair Square, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Arts & Culture",
    title: "Savannah Cultural Arts Center",
    description: "Community theater, gallery shows, and classes on Liberty Street.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Shopping",
    title: "ShopSCAD",
    description: "Student and alumni-designed jewelry, prints, and home goods.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Shopping",
    title: "E. Shaver Bookseller",
    description: "Independent bookstore with tea room and author events.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Golf",
    title: "Savannah Golf Championship Course",
    description: "TPC-level conditioning and tour-style practice facilities.",
    venue: "The Landings, Savannah",
    website: "https://www.landingsclub.com",
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Golf",
    title: "Crosswinds Golf Club",
    description: "Public course with pine-lined fairways near the airport.",
    venue: "Savannah",
    website: "https://www.crosswindsgolfclub.com",
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Family & Kids",
    title: "Savannah Children's Museum",
    description: "Outdoor play exhibits and STEM activities in a historic station.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Family & Kids",
    title: "Georgia State Railroad Museum",
    description: "Climbable locomotives and turntable demos on historic tracks.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Nightlife",
    title: "Club One Savannah",
    description: "Drag shows, dance floor, and late-night cocktails.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Nightlife",
    title: "Artillery Bar",
    description: "Craft cocktails in a historic artillery armory with courtyard seating.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Fitness & Wellness",
    title: "Savannah Yoga Center",
    description: "Heated flow, yin, and teacher training in a historic loft.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Fitness & Wellness",
    title: "Perry Lane Spa",
    description: "Rooftop pool passes and spa treatments in a luxury hotel setting.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "General",
    title: "Savannah Visitor Information Center",
    description: "Maps, trolley tickets, and trip planning inside a historic train shed.",
    venue: "Martin Luther King Jr. Boulevard, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Nightlife",
    title: "Electric Moon Skytop",
    description: "Rooftop lawn games, cocktails, and river views atop Plant Riverside.",
    venue: "Plant Riverside District, Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Arts & Culture",
    title: "Savannah VOICE Festival",
    description: "Annual classical voice performances in churches and theaters.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Outdoors & Nature",
    title: "McQueen's Island Trail",
    description: "Paved rails-to-trail ride with salt marsh views toward Tybee.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Food & Drink",
    title: "The Vault Kitchen & Market",
    description: "Kitchen market with chef’s counter, wine shop, and cooking classes.",
    venue: "Savannah",
    website: null,
    source: "curated",
  },
  {
    market_key: "savannah",
    category: "Water Sports",
    title: "Savannah River Queen Harbor Tours",
    description: "Narrated harbor cruises focusing on port history and wildlife.",
    venue: "Savannah River",
    website: null,
    source: "curated",
  },
];
